MeuProjeto/MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.home, name='home'), 
    
    path('curriculo/', include('curriculo.urls')), 
    
    path('parte2/', include('meu_app.urls')), 
]

MeuProjeto/MeuSite/curriculo/urls.py
from django.urls import path
from . import views

app_name = 'curriculo'

urlpatterns = [
    path('spiff/', views.curriculo_spiff, name='curriculo_spiff'),
    path('spiff/v2/', views.curriculo_spiff_v2, name='curriculo_spiff_v2'),
]

MeuProjeto/MeuSite/meu_app/urls.py
from django.urls import path
from . import views

app_name = 'meu_app' 

urlpatterns = [
    path('', views.index, name='index'), 
]

MeuProjeto/MeuSite/meu_app/models.py
from django.db import models

# Create your models here.

MeuProjeto/MeuSite/MeuSite/views.py
from django.shortcuts import render

def home(request):
    '''
    View function for home page of site.
    Renders the home.html template.
    '''
    return render(request, 'MeuSite/home.html')

MeuProjeto/MeuSite/curriculo/views.py
from django.shortcuts import render

def curriculo_spiff(request):
    return render(request, '../../../../../HTML/meu-curriculo.html')

def curriculo_spiff_v2(request):
    return render(request, 'curriculo/curriculo-v2.html')

MeuProjeto/MeuSite/meu_app/views.py
from django.shortcuts import render

def index(request):
    
   
    meu_nome = "Pedro Augusto Beserra da Silva"
    
    lista_ranking = [
        { 
            "titulo": "O Show de Truman: O Show da Vida", 
            "img": "https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/07/show-de-truman.jpeg?w=1000",
            
            "links": [
                { "desc": "Ver na Netflix", "url": "https://www.netflix.com/br/title/11819086" },
                { "desc": "Trailer", "url": "https://www.youtube.com/watch?v=0-t3hIGW4jY" }
            ]
        },
        { 
            "titulo": "Jojo Rabbit", 
            "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTJbtJ33VTLFKJ1kzOb5VRpIRf9B6ir284zw&s",
           
            "links": [
                { "desc": "Ver no IMDb", "url": "https://www.imdb.com/pt/title/tt2584384/" }
            ]
        },
        { 
            "titulo": "Forrest Gump: O Contador de Histórias", 
            "img": "https://m.media-amazon.com/images/I/91++WV6FP4L._AC_UF894,1000_QL80_.jpg",
            "links": [
                { "desc": "Ver no IMDb", "url": "imdb.com/pt/title/tt0109830/?reasonForLanguagePrompt=browser_header_mismatch" }
            ]
        }
    ]

   
    context = {
        'nome_pagina': meu_nome,
        'ranking': lista_ranking,
    }
    
   
    return render(request, 'index.html', context)

MeuProjeto/MeuSite/MeuSite/templates/MeuSite/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Home Page do MeuSite</h1>
    <h2>Links para os currículos</h2>
    <p>Teste Django</p>
    <img src="../../../curriculo/static/curriculo/img/" alt="">
    <ul>
        <li><a href="{% url 'curriculo:curriculo_spiff' %}">Currículo do Spiff</a></li>
        <li><a href="{% url 'curriculo:curriculo_spiff_v2' %}">Currículo responsivo do Spiff</a></li>
        <li><a href="{% url 'meu_app:index' %}">Parte 2 </a></li>
    </ul>
   <img src="../../../../../HTML/meu-curriculo.html" alt="">
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/curriculo-v1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Curriculo v1</h1>
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/curriculo-v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Curriculo2</h2>
</body>
</html>

MeuProjeto/MeuSite/meu_app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minha Página (Parte 2)</title>
    
    
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

    <header>
        <h1>Página de Tarefa</h1>
    
        <h2>{{ nome_pagina }}</h2>
    </header>

    <main>
        <h3>Meu Ranking de Filmes</h3>
        
      
        <div class="ranking-container">
            {% for item in ranking %}
                <div class="ranking-item">
                    
        
                    <img src="{{ item.img }}" alt="{{ item.titulo }}">
                    
                    <h4>{{ item.titulo }}</h4>


                    <ul>
                        {% for link in item.links %}
                            <li>
                                <a href="{{ link.url }}" target="_blank">{{ link.desc }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        
        <hr>

        <h3>Exemplo de Imagem Local</h3>

    </main>

</body>
</html>